### PR TITLE
align ar/noar quest naming

### PR DESCRIPTION
**Pull request by ccev**
drop stupid quest/alt quest naming

### CODE REVIEW

**Comment by Fabio1988** [comment]
imo that makes code really bad to read in future... We would need to change all occurences, also in the database

**Comment by jfberry** [comment]
We should not change the db schema just yet. Let’s just get the external naming right and fix the schema later

**Comment by jfberry** [comment]
If you wanted to make this clearer you could keep the alt naming for the db translation of the structure and output using the new naming in the json

**Comment by ccev** [comment]
i'm not sure where else this used. this is my quest to fix the naming from Turtle's recent Quest Status PR. AR/NoAR naming is used in Dragonite like this too. Imo it's a lot harder to understand Normal/Alt Quest naming

**Review by na-ji — APPROVED** [review]

**Pull request merged**
