### PR TITLE
quest status api

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- adds sql function to get list of quests in a geofence
- api endpoint to call the function

### CODE REVIEW

**Comment by jfberry** [comment]
This looks like it's the right idea here - I notice that the modules have been re-ordered in the files - is that goland that is doing that or some other editor?
The files were formated by `go fmt` I think, but perhaps this is updated in a newer version of go - just trying to understand what is behind this

**Comment by Fabio1988** [comment]
> This looks like it's the right idea here - I notice that the modules have been re-ordered in the files - is that goland that is doing that or some other editor? The files were formated by `go fmt` I think, but perhaps this is updated in a newer version of go - just trying to understand what is behind this

I used latest goland with default settings and my IDE is not reordering them, so might be external formattwer?!

**Comment by jfberry** [comment]
I can see why it has (external dependencies after internal and library). But it’s curious - wouldn’t want formatting to change with every commit

**Comment by Fabio1988** [comment]
We should definitely share our configs for fomatting, it seems that ours does match and Turtles not :)

**Comment by TurtIeSocks** [comment]
Probably a vsc formatting issue then. Got annoyed with goland and haven't gone back yet.

**Comment by lenisko** [comment]
@Fabio1988 or just add workflow and add post-commit 🤔

**Pull request merged**
