### PR TITLE
Fix Ditto lookup form

### PR DESCRIPTION
**Pull request by Mygod**
Form for ditto is set to disguise form. For queries, the form should be set to `UNSET`.

This should fix ReactMap filtering Ditto.

### CODE REVIEW

**Comment by Fabio1988** [comment]
Do I assume correctly that we store the disguise form only to distinguish the mon when we want to find the right disguise when encountering in game?

**Review by Fabio1988 — APPROVED** [review]

**Comment by Mygod** [comment]
Yep.

**Comment by jfberry** [comment]
Why is the form set to a non valid form in the db anyway? Surely this means all webhooks, etc are all wrong?

**Comment by Mygod** [comment]
> Do I assume correctly that we store the disguise form only to distinguish the mon when we want to find the right disguise when encountering in game?

^

**Comment by Fabio1988** [comment]
The form is set for reasons. Users want to know what to search for when they hunt the ditto.
the form could be important when there are two mons with different form on the same location

**Comment by jfberry** [comment]
That feels like the wrong thing to have done and is causing these knock on issues. Because webhooks would also need fixing at least

**Comment by Fabio1988** [comment]
I think that was always the case for ditto, also in RDM :)

**Comment by jfberry** [comment]
I suggest we don’t set the form to the disguise form then this pr is not needed

**Comment by Mygod** [comment]
And? Can't even bother to give any justification?

**Comment by Mygod** [comment]
How about I suggest we remove all Ditto related functionalities from Golbat then this PR is truly not needed.

**Comment by jfberry** [comment]
Because currently we have an invalid Pokemon/form combination and all users of the data are impacted. 
we store disguise Pokemon id elsewhere so would support a disguise form to go along with it
This feels like partial sticking plaster over data stored in the wrong place

**Comment by Mygod** [comment]
(If you do not wish to do that, then this PR is the second best option.)

**Comment by Fabio1988** [comment]
Even RDM is setting form to 0. 

https://github.com/RealDeviceMap/RealDeviceMap/blob/dd7a9fcc4c1b7ed4b040ec2502d9fb2421b5bc16/Sources/RealDeviceMapLib/Modell/Pokemon.swift#L1342

**Comment by jfberry** [comment]
Most applications would assume a valid Pokemon/form combination - I think rdm set form to 0
Fixing just for reactmap is not the best way forward

**Comment by Mygod** [comment]
Setting form to 0 is just introducing another bug to fix down the road. Feel free to choose this obviously worse option.

**Comment by Fabio1988** [comment]
> As I said this fix is not just fix for ReactMap. It fixes for every client that uses this query interface, including RM.

Tell me another one using it 😉 😂

**Comment by jfberry** [comment]
But then in the response we give an invalid form id
And in the webhook 
And in the database
What bug do we introduce by setting it to the correct form for ditto (0)
If storing the disguise form is important then let’s do that.

**Comment by Mygod** [comment]
> Most applications would assume a valid Pokemon/form combination

As you said, Ditto not only does not have a valid Pokemon/form combination, it does not have a valid Pokemon/form/gender/move combination either.

**Comment by jfberry** [comment]
These things are not relevant for identifying the Pokemon on the map whereas you can argue form is. 
but if you believe form is not then we can just set to 0 always like rdm does ?

**Comment by Mygod** [comment]
Just to be clear, you are seriously proposing to replace my "plaster" with an even worse "plaster". If that's the way you like it, then sure.

**Comment by jfberry** [comment]
> Just to be clear, you are seriously proposing to replace my "plaster" with an even worse "plaster". If that's the way you like it, then sure.

good

**Comment by Mygod** [comment]
Ditto is a special case no matter what and my PR does the minimal change, and indeed my PR sets the form to 0 but only for queries. Downstream should expect Ditto to be special no matter what.

**Comment by Mygod** [comment]
Downstream applications should always do a fallback to form 0 for handling missing masterfile updates anyways so it should not break anything.

**Comment by jfberry** [comment]
I think you are arguing that reactmap should be fixed and golbat is ok in its behaviour? Isn’t the point of your pr that downstream clients do not cope with this invalid combination?

**Comment by Mygod** [comment]
It's only for the query interface. The returned results will have the disguise forms as before.

**Comment by jfberry** [comment]
Right and if reactmap is accessing the database the same problem will be shown there?
And similarly any other client searching or processing data

**Comment by Mygod** [comment]
Okay good point.

**Pull request closed without merging**
