### PR TITLE
adapt checks for fort changes

### PR DESCRIPTION
**Pull request by Fabio1988**
this prevents webhooks send if e.g. Description changes from nil -> ""

Ready to review, Already checked out and running with that changes... Next changes incoming in about 4 hours hopefully, then I can check behavior

### CODE REVIEW

**Review by lenisko — APPROVED** [review]
Hopefully we won't get `"" => NULL` :)
Otherwise, looks good! 

Thank you!

**Comment by jfberry** [comment]
Did this actually happen? I can’t conceive of when it could?

**Comment by lenisko** [comment]
happened to me, once though.

**Comment by Fabio1988** [comment]
Tested since days, all good, notification webhooks are good. System stable

**Review by jfberry — APPROVED** [review]

**Pull request merged**
