### PR TITLE
Support for expert filter for in-memory Pokemon

### PR DESCRIPTION
**Pull request by Mygod**
Need corresponding support from @TurtIeSocks's ReactMap.

### CODE REVIEW

**Review by TurtIeSocks — APPROVED** [review]

**Comment by jfberry** [comment]
Please provide performance data. 
memquery has had several rounds to get performance to a good level and this will not be merged unless it is almost zero impact

**Comment by jfberry** [comment]
Example size would be 1,000,000 Pokémon scanned

**Comment by Mygod** [comment]
This is an optional feature that only gets called from ReactMap ONLY if you enable expert filter. With that said, for even an unreasonable large map zoom, the entire query (round trip time from browser request to the end of response) finishes within 1 second. On average, the expert filter takes about ~2x time as without, and obviously blows the alternative of using SQL out of the water. Currently there is no alternative way to support expert filters without using SQL.

**Comment by TurtIeSocks** [comment]
```
INFO 2023-04-23 04:58:07 GetPokemonInArea - total time 1.175475935s (locked time 1.040812767s), 1576700 scanned, 0 skipped, 2739 returned
```
Very worst case scenario, zoomed all the way out, 1.5m pokemon. IIRC about the same on `memquery` branch but I can check in the morning when quests aren't about to start.

**Comment by Mygod** [comment]
I am guessing that if we can find an `expr` alternative library that does not involve using reflection, then the performance could probably even potentially trade blows with the default filter.

**Comment by jfberry** [comment]
You didn’t quote the time without the filter. I don’t know performance of your machine. In our testing I would expect to be a few hundred ms using the standard filters

**Comment by jfberry** [comment]
Also given memory use is a concern any solution that makes use of dynamic memory will not be merged until we have proven the base solution does not leak so we can compare this additionally has no issues (we are struggling to point the finger as it is without your evidence @TurtIeSocks )

**Comment by jfberry** [comment]
> This is an optional feature that only gets called from ReactMap ONLY if you enable expert filter. With that said, for even an unreasonable large map zoom, the entire query (round trip time from browser request to the end of response) finishes within 1 second. On average, the expert filter takes about ~2x time as the default ReactMap filter, and obviously still blows the alternative of using SQL out of the water. Currently there is no alternative way to support expert filters without using SQL.

Remember the locked time here indicates the time that no additional Pokémon are added to the memory object. All gmo processing of golbat is paused. So it is not just end user response that matters!

**Comment by Mygod** [comment]
Just want to stress that this is an optional feature from the client side that is not normally used. Also not sure what you mean by dynamic memory. This PR only creates ephemeral objects in the heap.

**Comment by Mygod** [comment]
> > This is an optional feature that only gets called from ReactMap ONLY if you enable expert filter. With that said, for even an unreasonable large map zoom, the entire query (round trip time from browser request to the end of response) finishes within 1 second. On average, the expert filter takes about ~2x time as the default ReactMap filter, and obviously still blows the alternative of using SQL out of the water. Currently there is no alternative way to support expert filters without using SQL.
> 
> Remember the locked time here indicates the time that no additional Pokémon are added to the memory object. All gmo processing of golbat is paused. So it is not just end user response that matters!

Sounds like we should implement read-write locks and/or snapshots (immutable rtree) then?

**Comment by jfberry** [comment]
> Just want to stress that this is an optional feature from the client side that is not normally used. Also not sure what you mean by dynamic memory. This PR only creates ephemeral objects in the heap.

It compiles expressions and we do not know the behaviour of the library

**Comment by jfberry** [comment]
> Sounds like we should implement read-write locks and/or snapshots (immutable rtree) then?

It is already read/write locked. It’s possible that a copy of the rtree (under lock) could be made before processing but accessing the map also needs to be under read write lock so a lock free alternative to map would need to be found also. 
these changes would need to be measured independently for perf/mem to any compiled query mode but would be highly appreciated (my plan was to make standard query performant and stable for persecution without enough making it even more complicated)

**Comment by Mygod** [comment]
Sure. Anyway this is written and the performance is not too bad. Feel free to merge when ready. :)

**Comment by jfberry** [comment]
> Sure. Anyway this is written and the performance is not too bad. Feel free to merge when ready. :)

It feels like it is >2s slower (with filters perhaps only at one level rather than both?). How does this degrade with expression complexity? Is it possible to dos the server? Given it is not a lock free area of the system it is critical to understand the performance implications.

**Comment by ccev** [comment]
What does "Expert filter" mean?

**Comment by Mygod** [comment]
@jfberry In reality most of the users are not going to use this feature, so the performance hit is minimal. So there are only two reasons not to merge this: (1) we need to investigate possible memory leak in #105 first and (2) possible (D)DoS atttacks. Personally, I am not very concerned about the possibility of DDoS attacks. If someone wants to do it, they can do it already even without this PR. This attack is already possible in #105 and I don't think this PR makes it significantly easier to carry out those attacks. Obviously having lock-free queries would solve (2) but a good way to mitigate the attack until then is to simply disallow free users from querying the in-memory cache.

@ccev It is a feature in ReactMap (that comes from MapJS) that allows the user to filter Pokemon with an arbitrary formula on the Pokemon IV.

**Comment by jfberry** [comment]
Without proper benchmarking this is going nowhere.
We at least need to know:
1. What the performance cost is;
2. Whether this is legitimately the best we can do, and whether this is actually reasonable not "it seems ok"

I've suggested a couple of ways to make it faster already  ... and some basic desktop research suggests a different evaluator may have different performance characteristics

**Comment by ccev** [comment]
Got it. Thanks for clarifying. I think the "Expert filter" naking is way too non-descriptibr for something (most likely) exclusively used by ReactMap and it being a pretty niche feature. Maybe rename it to "MapJsExpertFilter"?

**Comment by Mygod** [comment]
@ccev How does `MapJsExpertFilter` solve the issue of being non-descriptive? 😂

**Comment by ccev** [comment]
It makes the context clearer. If you have an idea for a more descriptive name, feel free to use that

**Comment by TurtIeSocks** [comment]
Results from #105 and this PR:

```
#105
INFO 2023-04-24 03:54:12 GetPokemonInArea - total time 1.415570473s (locked time 1.232037568s), 1825031 scanned, 0 skipped, 1633 returned
INFO 2023-04-24 03:54:16 GetPokemonInArea - total time 1.217684364s (locked time 1.186743631s), 1826671 scanned, 0 skipped, 1640 returned
INFO 2023-04-24 03:54:17 GetPokemonInArea - total time 1.265180366s (locked time 1.233217156s), 1826670 scanned, 0 skipped, 1640 returned
INFO 2023-04-24 03:54:18 GetPokemonInArea - total time 1.084572423s (locked time 1.056283638s), 1826646 scanned, 7 skipped, 1640 returned
INFO 2023-04-24 03:54:19 GetPokemonInArea - total time 1.370277431s (locked time 1.338942156s), 1826647 scanned, 9 skipped, 1639 returned
INFO 2023-04-24 03:54:21 GetPokemonInArea - total time 1.612083686s (locked time 1.583846199s), 1826646 scanned, 9 skipped, 1639 returned
INFO 2023-04-24 03:54:22 GetPokemonInArea - total time 1.531184408s (locked time 1.502814154s), 1826645 scanned, 9 skipped, 1639 returned
INFO 2023-04-24 03:54:23 GetPokemonInArea - total time 1.99482974s (locked time 1.962396348s), 1826644 scanned, 9 skipped, 1639 returned
INFO 2023-04-24 03:54:24 GetPokemonInArea - total time 1.805716491s (locked time 1.770717083s), 1826645 scanned, 10 skipped, 1638 returned
INFO 2023-04-24 03:54:25 GetPokemonInArea - total time 1.662287418s (locked time 1.596308052s), 1826644 scanned, 10 skipped, 1637 returned
INFO 2023-04-24 03:54:27 GetPokemonInArea - total time 1.601456092s (locked time 1.351392332s), 1828321 scanned, 0 skipped, 1643 returned
INFO 2023-04-24 03:54:30 GetPokemonInArea - total time 1.153146871s (locked time 1.119281578s), 1829588 scanned, 0 skipped, 1644 returned
INFO 2023-04-24 03:54:31 GetPokemonInArea - total time 1.512833563s (locked time 1.445395119s), 1829587 scanned, 0 skipped, 1643 returned
INFO 2023-04-24 03:54:41 GetPokemonInArea - total time 1.633963233s (locked time 1.353055605s), 1834439 scanned, 0 skipped, 1651 returned

# 108
INFO 2023-04-24 03:11:56 GetPokemonInArea - total time 1.361737951s (locked time 1.192375662s), 1864537 scanned, 0 skipped, 1804 returned
INFO 2023-04-24 03:12:06 GetPokemonInArea - total time 1.371810303s (locked time 1.193301204s), 1864554 scanned, 0 skipped, 1802 returned
INFO 2023-04-24 03:12:11 GetPokemonInArea - total time 1.44963093s (locked time 1.339434524s), 1864577 scanned, 0 skipped, 1798 returned
INFO 2023-04-24 03:12:12 GetPokemonInArea - total time 1.12863505s (locked time 1.079143625s), 1864583 scanned, 0 skipped, 1797 returned
INFO 2023-04-24 03:12:15 GetPokemonInArea - total time 1.122767387s (locked time 1.075535477s), 1864466 scanned, 0 skipped, 1794 returned
INFO 2023-04-24 03:12:16 GetPokemonInArea - total time 1.129135287s (locked time 1.01417155s), 1864037 scanned, 76 skipped, 1794 returned
INFO 2023-04-24 03:12:17 GetPokemonInArea - total time 1.378592439s (locked time 1.112355229s), 1863479 scanned, 0 skipped, 1794 returned
INFO 2023-04-24 03:12:18 GetPokemonInArea - total time 1.042563653s (locked time 1.000560916s), 1864241 scanned, 0 skipped, 1793 returned
INFO 2023-04-24 03:12:19 GetPokemonInArea - total time 1.125728925s (locked time 1.084492166s), 1864240 scanned, 0 skipped, 1793 returned
INFO 2023-04-24 03:12:21 GetPokemonInArea - total time 1.338139699s (locked time 1.266508191s), 1864240 scanned, 0 skipped, 1791 returned
```

**Comment by jfberry** [comment]
> Results from #105 and this PR:
> 
> ```
> #105
> INFO 2023-04-24 03:54:12 GetPokemonInArea - total time 1.415570473s (locked time 1.232037568s), 1825031 scanned, 0 skipped, 1633 returned
> INFO 2023-04-24 03:54:16 GetPokemonInArea - total time 1.217684364s (locked time 1.186743631s), 1826671 scanned, 0 skipped, 1640 returned
> INFO 2023-04-24 03:54:17 GetPokemonInArea - total time 1.265180366s (locked time 1.233217156s), 1826670 scanned, 0 skipped, 1640 returned
> INFO 2023-04-24 03:54:18 GetPokemonInArea - total time 1.084572423s (locked time 1.056283638s), 1826646 scanned, 7 skipped, 1640 returned
> INFO 2023-04-24 03:54:19 GetPokemonInArea - total time 1.370277431s (locked time 1.338942156s), 1826647 scanned, 9 skipped, 1639 returned
> INFO 2023-04-24 03:54:21 GetPokemonInArea - total time 1.612083686s (locked time 1.583846199s), 1826646 scanned, 9 skipped, 1639 returned
> INFO 2023-04-24 03:54:22 GetPokemonInArea - total time 1.531184408s (locked time 1.502814154s), 1826645 scanned, 9 skipped, 1639 returned
> INFO 2023-04-24 03:54:23 GetPokemonInArea - total time 1.99482974s (locked time 1.962396348s), 1826644 scanned, 9 skipped, 1639 returned
> INFO 2023-04-24 03:54:24 GetPokemonInArea - total time 1.805716491s (locked time 1.770717083s), 1826645 scanned, 10 skipped, 1638 returned
> INFO 2023-04-24 03:54:25 GetPokemonInArea - total time 1.662287418s (locked time 1.596308052s), 1826644 scanned, 10 skipped, 1637 returned
> INFO 2023-04-24 03:54:27 GetPokemonInArea - total time 1.601456092s (locked time 1.351392332s), 1828321 scanned, 0 skipped, 1643 returned
> INFO 2023-04-24 03:54:30 GetPokemonInArea - total time 1.153146871s (locked time 1.119281578s), 1829588 scanned, 0 skipped, 1644 returned
> INFO 2023-04-24 03:54:31 GetPokemonInArea - total time 1.512833563s (locked time 1.445395119s), 1829587 scanned, 0 skipped, 1643 returned
> INFO 2023-04-24 03:54:41 GetPokemonInArea - total time 1.633963233s (locked time 1.353055605s), 1834439 scanned, 0 skipped, 1651 returned
> 
> # 108
> INFO 2023-04-24 03:11:56 GetPokemonInArea - total time 1.361737951s (locked time 1.192375662s), 1864537 scanned, 0 skipped, 1804 returned
> INFO 2023-04-24 03:12:06 GetPokemonInArea - total time 1.371810303s (locked time 1.193301204s), 1864554 scanned, 0 skipped, 1802 returned
> INFO 2023-04-24 03:12:11 GetPokemonInArea - total time 1.44963093s (locked time 1.339434524s), 1864577 scanned, 0 skipped, 1798 returned
> INFO 2023-04-24 03:12:12 GetPokemonInArea - total time 1.12863505s (locked time 1.079143625s), 1864583 scanned, 0 skipped, 1797 returned
> INFO 2023-04-24 03:12:15 GetPokemonInArea - total time 1.122767387s (locked time 1.075535477s), 1864466 scanned, 0 skipped, 1794 returned
> INFO 2023-04-24 03:12:16 GetPokemonInArea - total time 1.129135287s (locked time 1.01417155s), 1864037 scanned, 76 skipped, 1794 returned
> INFO 2023-04-24 03:12:17 GetPokemonInArea - total time 1.378592439s (locked time 1.112355229s), 1863479 scanned, 0 skipped, 1794 returned
> INFO 2023-04-24 03:12:18 GetPokemonInArea - total time 1.042563653s (locked time 1.000560916s), 1864241 scanned, 0 skipped, 1793 returned
> INFO 2023-04-24 03:12:19 GetPokemonInArea - total time 1.125728925s (locked time 1.084492166s), 1864240 scanned, 0 skipped, 1793 returned
> INFO 2023-04-24 03:12:21 GetPokemonInArea - total time 1.338139699s (locked time 1.266508191s), 1864240 scanned, 0 skipped, 1791 returned
> ```

With what filters?
What advanced filter did you use? 
what happens when you have advanced filters at both global and specific Pokémon level?
How does increasing the complexity of advanced filter change scan time?

**Comment by Fabio1988** [comment]
Why do we want that filter? It's old school and legacy... Also used in RDM.. nobody knows how to use it 😂

**Comment by Mygod** [comment]
It's not old school and legacy. It's expert and better (although admittedly harder to use). I personally use it every day. 😢

**Comment by TurtIeSocks** [comment]
It'd be better to optimize this in the long run and RM can send all queries in this form. Enabling a lot more filtering possibilities in the future.

**Comment by Fabio1988** [comment]
So RM would use that in background? Not usable of anybody on my community if they have to write that monster on their own :)

**Comment by jfberry** [comment]
> It'd be better to optimize this in the long run and RM can send all queries in this form. Enabling a lot more filtering possibilities in the future.

The opposite is actually true. Including this restricts future changes to storage types as it likely requires an iteration of all Pokémon rather than pre-calculation of result sets. 

It’s a niche requirement that has not yet been properly benchmarked - but at least changes elsewhere now mean extended runtime does not harm pokemon processing any longer 

still waiting for performance information before making a decision

**Comment by TurtIeSocks** [comment]
> So RM would use that in background? Not usable of anybody on my community if they have to write that monster on their own :)

RM will remove all sliders and only use this front and back.

**Comment by jfberry** [comment]
> > So RM would use that in background? Not usable of anybody on my community if they have to write that monster on their own :)
> 
> RM will remove all sliders and only use this front and back.

This would undo all future optimisation possibility and is a good reason to block this pr and forget the fast processing objective. You are obviously misaligned on simplification and performance

**Comment by Mygod** [comment]
You're proposing to remove functionalities for your disillusioned "performance"? It's forking time baby.

**Comment by Mygod** [comment]
While you're at it, don't forget to optimize out the functionality to query Pokemon altogether. The "fast processing objective" will be truly achieved and performance will then skyrocket. 🚀

**Comment by jfberry** [comment]
> You're proposing to remove functionalities for your disillusioned "performance"? It's forking time baby.

I am proposing, and always have been, to make core retrieval capability as instant as possible - at the expense of generic retrieval. 
Technologies like elastic (and sql server) are super fast with tagged data. We got into this hole with terrible sql queries. 

I am not suggesting golbat removes current database support - I am evaluating what it supports for new api query mechanisms so I am not held back from my future objectives. 

My understanding is this was aligned with turtle’s dream map idea. If it’s not then the whole thing is a waste of time. 

In the meantime, this PR will be evaluated based on hard performance metrics which have not yet been provided - as you can continue to use sql to get this level of flexibility should it be meaningful to you (and you are likely the only user in the world that cares about this)

**Comment by Mygod** [comment]
At the moment, all realistic queries with #108 enabled finish within 500ms (counting the entire network round trip time), and I don't see what's the point of further optimizations (especially at the cost of not merging new features) when the overall speed is on the same order as network latency.

What do I mean by realistic queries? Nobody is going to query 2 million Pokemon at a time except for cheaters: you cannot drive that fast.

Also if you do believe that I am the only user of this feature, then what's so bad about merging this? None of this code is going to be run in most of the time so you get zero performance impact even if my PR runs like shit.

**Comment by jfberry** [comment]
I would like to see the results from the timing that is in the application:
1. With queries at the global level only
2. With queries at both global and per pokemon level

For a variety of sizes of views.  
The log entry contains an accurate list of number of pokemon scanned, so comparisons with and without the filter in place can be made.

I'd like to understand what happens when complexity of the expression increases - does this cause any difference to the timing?

Reactmap makes the same query repeatedly, and turtle is suggesting using this more broadly (which I would oppose) as a generic query mechanism.  Even having this as a possibility discourages the correct api development behaviour.

Once this is in the API, then it restricts the ability to continue to tune the back-end using tagging (this would force a fall back to a full scan - or writing complex queries for whatever backend we might choose to use).  Both these restrictions may not apply to the fixed query set.   

Since you are likely one of the very few (if not only) user, then it makes it easier to deprecate this in the future if there is a problem - but since there are a low number of users I wonder if this should be something that we don't try and support through in memory queries and you can just query the database.

The only quoted performance figures that I've seen so far have been in DMs, and they haven't been measured with any science.  The lack of wishing to actually reveal the performance makes me even more cynical about the value of this.

**Comment by Mygod** [comment]
Okay sorry so I misunderstood. So there are two things being discussed here: (1) merging this and (2) using this API to replace the existing API. I propose that we postpone the discussion of (2) and focus on (1) first, since this PR is not about (2) at all. We can discuss that separately in the future but for now it is a waste of time.

Again, let me reiterate the point that all realistic queries on the map are being handled within 500ms, with or without #108. Even if you take your optimizations to the extreme, you are only reducing that 500ms down to maybe 50ms (unless you wish to invent superluminal signaling and break general relativity), but at the same time sacrificing the performance of expert filters or even the option of having an expert filter.

Golbat's performance is good enough as is and I don't think anyone is asking for such an aggressive trade-off.

> The lack of wishing to actually reveal the performance makes me even more cynical about the value of this.

I would give you performance data if I actually run a map. However, a gentle reminder that I don't so I literally do not have the capability to give you any data, instead of aggressively holding back data as you may have suggested.

**Comment by Mygod** [comment]
Also you are contradicting yourself. If you believe this is an important feature that could be used by many, then you should help with benchmarking to get this merged: everything is public and there is nothing holding you back from doing so. On the other hand, if you think this is a niche feature, then the hit to your performance is nil and there is again no reason not to merge this even if the performance is crap (which it is not).

**Comment by jfberry** [comment]
If you aren't prepared to

**Comment by Mygod** [comment]
If you can't handle rational criticisms and just want to be rude, then you can fuck right off

**Comment by jfberry** [comment]
I have been consistent in asking for the same data since very early on
I have worked hard to make sure that performance wasn't the blocked by removing locks to allow longer running queries
You seem to not want to help me evaluate your suggested change to a level of reasonable diligence. That's up to you; when you change your mind feel free to re-open this PR and provide the information I've asked for.

**Comment by Mygod** [comment]
Sure I appreciate your work but what makes you think that the work I put into #108 is trivial, as I seemed to infer from your tone?

Also you completely ignored my point:

> Also you are contradicting yourself. If you believe this is an important feature that could be used by many, then you should help with benchmarking to get this merged: everything is public and there is nothing holding you back from doing so. On the other hand, if you think this is a niche feature, then the hit to your performance is nil and there is again no reason not to merge this even if the performance is crap (which it is not).

So which side are you on? I have explained why merging this does not impact performance. Could you kindly care to explain why you think otherwise?

**Comment by Mygod** [comment]
> [Premature optimization is the root of all evil.](https://ubiquity.acm.org/article.cfm?id=1513451)

It looks like we are headed straight towards hell. RIP. 😞

**Pull request closed without merging**
