### PR TITLE
add raid pokemon alignment

### PR DESCRIPTION
**Pull request by Fabio1988**
followed same structure as in RDM https://github.com/RealDeviceMap/RealDeviceMap/pull/523

### CODE REVIEW

**Comment by jfberry** [comment]
lgtm (assuming you have tested it!)

**Comment by Mygod** [comment]
This is technically a redundant field since raid level also indirectly shows alignment? (Up until now.)

**Comment by Fabio1988** [comment]
Untested yet.. 
Using raid level might not be the right choice. This alignment is also used in wild pokemon, who knows, maybe Niantic let them spawn in the future ;)

**Comment by Fabio1988** [comment]
works as intended. column is properly filled with values, no crashes, all fine :) 
lgtm if nobody is against that additional column?!

**Pull request merged**
