### PR TITLE
Showcase decode

### PR DESCRIPTION
**Pull request by jfberry**
** NOTE: ATLAS DOES NOT CURRENTLY SUPPORT THIS PROTO **

This PR captures my work around decoding the showcase detail protocols.  My intention is to provide a minimum viable decode, rather than a future proof one.  I will work with map makers, etc to get the right level of information and no more.  This is because there is still a lot we haven

Some observations:
* Max number of entries is not in the proto
* Size is the only contest type
* incident id is not in any of the contest protocols, meaning any attempt to store this data on the incident row would require searching for it which may be fragile (or incident may not be present yet)
* Some showcases have >100 entries, and storing these seems to be of low value
* The request is needed for `GetPokemonSizeContestEntry` since the only way to get the 'fortId' is from the contest id in the request
* All the information about the contest can be obtained from GetPokemonSizeContestEntry aside from the end time and schedule information (which are only in `GetContestData`)

Implementation:
* Decode GetPokemonData to store the pokemon id, metric, and end time. This can be done just with the response 
* From GetPokemonSizeContestEntry (requires request)
  * Decode top 3 ranking pokemon and store these including form, costume etc (for fancy display) in a json field.

This would creates just four extra fields on pokestop:

```golang
ShowcasePokemon            null.Int    `db:"showcase_pokemon_id" json:"showcase_pokemon_id"`
ShowcaseRankingStandard    null.Int    `db:"showcase_ranking_standard" json:"showcase_ranking_standard"`
ShowcaseExpiry             null.Int    `db:"showcase_expiry" json:"showcase_expiry"`
ShowcaseRankings           null.String `db:"showcase_rankings" json:"showcase_rankings"`
```

### CODE REVIEW

**Comment by clburlison** [comment]
> From GetPokemonSizeContestEntry -
Decode pokemon focus from request, and store this in pokemon table

This is the only part that confuses me. Did you mean the Pokestop table?

**Comment by Fabio1988** [comment]
Thanks for extracting the information:
I agree on all points. as we don't get information about incident id we might need to store that information on pokestop itself, or a new table.

> There may be an argument to add the end time to the pokestop as well so you don't have to cross reference to invasion (requiring the GetContestData decode).
> 
> On reflection, I don't think storing the full entries, or extracting the top-3 pokemon into scores directly on the table, provides many benefits at this stage (although open for debate)

When we store without any time on pokestop table, the columns will have data also when the contest is not enabled or when contests are switching stops after season.  
Frontend should only show the showcase if the user is filtering for them. not sure if RM can work like that on two different tables? @TurtIeSocks

**Comment by Fabio1988** [comment]
i had an exhausting discussion with my community of show-case mapping. Hunting XXL with the map is very easy, so those already have an advantage. The points are still missing, so someone playing the game does not see show-case member points before attending. showing those points would give every map user an unfair advantage.

many of those XXL hunter do not attend the showcase until 30 minutes before the end of the showcase. So there is a lot happening in the last 30 minutes. There is also a [bug](https://niantic.helpshift.com/hc/en/6-pokemon-go/faq/4167-pokemon-cannot-be-switched-in-a-pokestop-showcase-once-the-contest-limit-is-reached/) were you can't switch pokemon if you reached contest limit of 3.

So yes it is nice to show the contest itself, but points not. would be nice to keep points behind a toggle in any Frontend / Webhook listener supporting showcases.

Me as admin would definitely disable points for my community, because it leads to an unfair advantage for map only users. Because this information is not even visible ingame, until you take part of the showcase (only 2 more showcases left after)

**Comment by Mygod** [comment]
The bug was resolved already. I agree that it's nice to have a toggle but since there is a 3-mon limit for each account, I don't think the possibility of cheating is that concerning.

By the way, you can also see the points of a contest, unjoin the contest by switching a different stop showcase to the Mon you joined, then repeat. This means that a legit player could also mass hunt showcases in principle.

**Comment by Mygod** [comment]
Well it sounds like that it's more important to have a toggle for displaying/filtering sizes than showcase points. :)

**Comment by jfberry** [comment]
@TurtIeSocks this now writes to the database, so ready for map support when you get a moment
I chose to put the expiry date on the pokestop table as this could be long standing (after the incident has disappeared) and represents the end time of the last showcase on the stop

**Comment by Mygod** [comment]
Well as discussed in #125, since the contest scores and the number of entries are not separate columns, it would be inefficient for map to filter by those. (A very weak argument could be made that this way it would be harder to be toxic.)

> Max number of entries is not in the proto
https://github.com/UnownHash/Golbat/issues/125#issuecomment-1625359437

**Pull request merged**
