### PR TITLE
Implement RTrees for faster geographic matching

### PR DESCRIPTION
**Pull request by jfberry**
Golbat isn't fast enough.
MOOOREEE SPEEED.

Issue: #88

### CODE REVIEW

**Comment by Mygod** [comment]
You can use Max Airstream for more speed, or Agility if +1 is not enough. 😃

**Comment by ringsaturn** [comment]
If need more performance improvements, consider use point-in-polygon from https://github.com/tidwall/geojson, it has a QuadTree/RTree index for polygon’s points https://github.com/tidwall/geojson/issues/23 which is much faster compared with orb’s geojson.

**Comment by jfberry** [comment]
> If need more performance improvements, consider use point-in-polygon from https://github.com/tidwall/geojson, it has a QuadTree/RTree index for polygon’s points [tidwall/geojson#23](https://github.com/tidwall/geojson/issues/23) which is much faster compared with orb’s geojson.

This is a great find, as it would likely have provided the optimisation for us automatically.
I suspect the performance we see now is equivalent as the point in polygon is, I think, the same algorithm and using the rtree to select which polygons to test just as we are now.
Certainly introducing the rtree has made a substantial difference for installations with a large number of polygons and we are now experimenting with it for direct retrieval of pokemon from the cache avoiding sql lookups.

**Comment by jfberry** [comment]
> If need more performance improvements, consider use point-in-polygon from https://github.com/tidwall/geojson, it has a QuadTree/RTree index for polygon’s points [tidwall/geojson#23](https://github.com/tidwall/geojson/issues/23) which is much faster compared with orb’s geojson.

Ps, didn't realise you were the maintainer of tzf - thanks, we love it

**Pull request merged**
