### PR TITLE
Replace player ID by auto incremented int

### PR DESCRIPTION
**Pull request by na-ji**
The goal of this PR is to make the player table compatible with _another tool_.

### CODE REVIEW

**Comment by jfberry** [comment]
The problem with this is that if another tool is holding this data, and sending raws to golbat the ids will not be aligned - since it is an auto-increment field

**Comment by na-ji** [comment]
> The problem with this is that if another tool is holding this data, and sending raws to golbat the ids will not be aligned - since it is an auto-increment field

Golbat is using the username to find and update player data. So how is it an issue?

**Comment by jfberry** [comment]
Is this confirmed as the way you want to go? Or holding out for recent raid changes?

**Comment by na-ji** [comment]
No it's not, hence why I made the PR a draft. In the end, I will go this way: 
https://discord.com/channels/973641026117972038/1023686446671999046/1065895293939372104
But for that, I need to be able to parse the request

**Pull request merged**
