### PR TITLE
Do not save capture rate in db

### PR DESCRIPTION
**Pull request by TurtIeSocks**
Removes capture rate from the db, since it's entirely useless. Still sends in webhooks though.

Based off of #65 , merge that one first

### CODE REVIEW

**Comment by Fabio1988** [comment]
Why useless? Not used in ReactMap? Which impact on storing that information?

**Comment by Mygod** [comment]
These rates differ by account (catch badges). See also: https://github.com/WatWowMap/Chuck/pull/29

**Comment by TurtIeSocks** [comment]
ReactMap does not use this info, due to it being inaccurate for everyone.

**Comment by jfberry** [comment]
Will need rebasing

**Comment by TurtIeSocks** [comment]
Should we also drop the columns and webhook data?

**Comment by Fabio1988** [comment]
As I can think of only Poracle uses it. somebody could reference it in the DTS

https://github.com/KartulUdus/PoracleJS/blob/develop/src/controllers/monster.js#L215

**Comment by Mygod** [comment]
#65 already stopped processing the rates btw. 😝

**Comment by jfberry** [comment]
> > It's right the data parser doesn't record them; the question is whether we should include them in webhooks by calculation magic (or someone should provide a PR to poracle)
> 
> As in each user would save their gym badges to the poracle table to do calculations?

I meant base rates

**Comment by Mygod** [comment]
*Catch badges, not gym badges. :)

**Comment by TurtIeSocks** [comment]
> So for providing the catch rates in front-end we need at least the cpMultiplier, that's part of the pokemon proto. So we would need a possibility to gather that information for every mon
> 
> is the base cpMultiplier in gamemaster available @TurtIeSocks  ?

I don't believe so. But the jsons are available in many places

**Comment by Fabio1988** [comment]
already done in #74 
can we create an issue to not forget this?

**Comment by ccev** [comment]
I'm not really sure why you'd need CPMs from the gamemaster. to calculate a catch rate, you need

- the Pokemon's CPM (provided by Golbat)
- the Pokemon's base capture rate (provided by the gamemaster, in the Mon's pokemon settings)
- certain modifiers (balls, berries, medals, etc) (hardcoded values in the game's backend, can be found on the internet)

**Comment by Fabio1988** [comment]
> I'm not really sure why you'd need CPMs from the gamemaster. to calculate a catch rate, you need
> 
>     * the Pokemon's CPM (provided by Golbat)
> 
>     * the Pokemon's base capture rate (provided by the gamemaster, in the Mon's pokemon settings)
> 
>     * certain modifiers (balls, berries, medals, etc) (hardcoded values in the game's backend, can be found on the internet)

CPM=cpMultiplier ?
yeah it's in golbat, but it varies on the worker, true? if a worker achieves normal catch medal this will be different, no?
#79 we should continue discussion in that gh issue :)

**Pull request closed without merging**
