### PR TITLE
adds missing ditto columns to sqlite migration

### LINKED ISSUE #93: in_memory option is broken
For future peeps keep the `in_memory` option set to disabled for now. MyGod added a bunch of ditto detection code and someone, _cough_ Turtle _cough_, promises to get this added.

If you see the following error messages that's why.

```
ERRO 2023-03-30 22:42:02 Error pokemon [XXXXXXXXXXXX]: no such column: iv_inactive
ERRO 2023-03-30 22:42:02 getOrCreatePokemonRecord: no such column: iv_inactive
ERRO 2023-03-30 22:42:02 Error pokemon [XXXXXXXXXXXX]: no such column: iv_inactive
ERRO 2023-03-30 22:42:02 getOrCreatePokemonRecord: no such column: iv_inactive
ERRO 2023-03-30 22:42:02 getOrCreatePokemonRecord: no such column: iv_inactive
ERRO 2023-03-30 22:42:02 getOrCreatePokemonRecord: no such column: iv_inactive
```

### PR DESCRIPTION
**Pull request by TurtIeSocks**
- Resolves #93

### CODE REVIEW

**Comment by clburlison** [comment]
This fixes one issue but now there's a new one.

```
INFO 2023-03-30 23:33:40 getOrCreatePokemonRecord: no such column: is_ditto
```

Thought adding 
```
is_ditto TINYINT DEFAULT 0,
```
to that same file would fix it but I was wrong :)

**Comment by Fabio1988** [comment]
is_ditto is still missing in that file, thanks for report :)

**Review by Fabio1988 — APPROVED** [review]

**Comment by lenisko** [comment]
https://github.com/UnownHash/Golbat/blob/ef8cf2ec997a9c32d12c84047a6aec48e8fec66c/sql/sqlite/create.sql#L26

I think this should be `REAL`. Other than that, changes look correct.

**Review by lenisko — APPROVED** [review]
https://github.com/UnownHash/Golbat/blob/ef8cf2ec997a9c32d12c84047a6aec48e8fec66c/sql/sqlite/create.sql#L26

I think this should be `REAL`. Other than that, changes look correct.

**Pull request merged**
